LlibertadApp/frontend

src/components/protectedRoute/protectedRoute.tsx, src/routes/routes.tsx
En resumen:
-    Agregue un componente que se llama protectedRoute, el cual verifica que exista el usuario, en caso contrario lo retorna al login.
- Agregue protectedRoute a Routes.
=> Add Protected Route Middleware

src/hooks/utils/useAxios.tsx, src/pages/login/login.tsx
Hice este PR para determinar la direccion que queremos en el useAxios, basicamente lo cambie para que el estado en el momento de la request este en un state que retorna el hook, de esta forma el estado actual de la llamada es accesible por todo el componente, asi pudiendo cambiar la UI acorde a si esta cargando o hay un error, en el formato actual lo que pasa es que espera a que termine y nos tira el resultado final, nunca pasando por loading ya que ya awaiteó la llamada. Este patron que elegimos nos fuerza a hacer un poco mas grande al componente, reaccionando siempre a los 3 casos en un useEffect o en el propio render, pero tambien es simple y entendible, otra cosa mala es que tenemos que declarar 2 hooks si tenemos 2 llamadas simultaneas.
=> New Use Axios

src/components/navbar/index.tsx
=> navbar - back arrow size set to match hamburger menu button size using css grid

src/components/navbar/index.tsx
No se aplicó los fixes visuales de los filtros sobre el menu hamburguesa
=>  Same Bug on /navbar "Z-Index 20" on /filter-results 

src/pages/not-found/notFound.tsx, tailwind.config.js
=> Redesign with new 404 page layout

public/assets/icon/failed.svg, src/pages/send-success/sendSuccess.tsx, src/pages/total-results/totalResults.tsx, src/pages/upload-failed/uploadFailed.tsx, src/routes/routes.tsx
=> Upload-failed-page added

package.json
Estos componentes son los q se ven en el Figma q vamos a utilizar.
=> feat: agrega Material UI al Proyecto

.gitignore, package.json, src/components/navbar/index.tsx, src/components/uploadImage/index.tsx, src/context/AuthContext.tsx, src/pages/home/home.tsx, src/pages/load-information/loadInformation.tsx, src/pages/login/login.tsx, src/pages/not-found/notFound.tsx, src/pages/profile/profile.tsx, src/pages/results/filter.tsx, src/pages/send-success/sendSuccess.tsx, src/pages/total-results/totalResults.tsx, src/pages/upload-certificate/uploadCertificate.tsx, src/pages/upload-failed/uploadFailed.tsx, src/pages/verify-certificate/verifyCertificate.tsx, src/routes/pathGen.js, src/routes/pathTree.js, src/routes/routes.tsx, tsconfig.json
Generador de rutas al buildear, lo bueno es que te genera todo el path hasta las rutas, en esta app no tenemos rutas nesteadas pero está preparado para esos casos. Dejo aca un ejemplo de una app mas grande, para que se entienda como se genera el paths file:
De esta forma podes acceder a la seccion que necesites con el pathThree (ejemplo quiero solo newObservation): `pathTree.monitoring.newObservation.path === "new-observation/:patientID"`
O a toda la ruta hacia newObservation:
`paths.newObservation === "/monitoring/new-observation/:patientID"`
**pathTree.js**
```
export const pathTree = {
path: '',
auth: {
path: 'auth',
signin: {
path: 'signin',
},
forgotPassword: {
path: 'forgot-password',
},
},
patients: {
path: 'patients',
newPatient: {
path: 'new-patient',
},
editPatient: {
path: …
```
=> Route Generator

src/App.tsx, src/context/AuthContext.tsx
Fixes for axios branch:
* Moving LoaderProvider up the hierarchy 
* Wrapping functions in useCallback
=> Axios fixes

package.json, src/context/AuthContext.tsx
En resumen:
- Hice una validacion en auth context, al momento de ejecutar refreshtoken(), para verificar que el token no estuviera vencido.
=> Validate token exp date

src/components/navbar/index.tsx, src/components/overlay/index.tsx
Version actual (dev): 
Version propuesta en figma: 
Version final:
=> [FIX]: Hamburger menu styles (when open)

src/components/uploadImage/index.tsx, src/pages/load-information/loadInformation.tsx, src/pages/verify-certificate/verifyCertificate.tsx
=> minor style fixes on btns

src/pages/load-information/loadInformation.tsx
=> fix NaN issue on formik input fields

src/index.css
=> fix: fonts url

src/App.css, src/components/flatList/index.tsx, src/pages/load-information/loadInformation.tsx
=> Fixed Flat list containers

src/pages/load-information/loadInformation.tsx
Solucione el Bug del contenedor Gigante en vista Web de diferencia de votos
=> Fixed UI votesDifferences_ResponsiveWebFix

src/App.css, src/components/selector/index.tsx, src/components/selector/styles.css
=> fix: selector menu styles

src/pages/desk-list/deskList.tsx, src/pages/home/home.tsx, src/routes/paths.ts, src/routes/routes.tsx
=> Vista DeskList, and UI

src/hooks/utils/use-select-data.ts, src/mocks/_mocks.ts, src/pages/filter-results/filter-results.tsx
Creé un hook para traer los datos de los selects del filtro. Hice mocks para los datos, más adelante hay que traerlos de backend.
=> add mocks for selects (filter-result)

src/pages/desk-list/deskList.tsx, src/pages/irregularities/irregularities.tsx
Fixes siguiendo el ultimo diseño del figma y correcion de typos.
=> Fixes UI Mesas cargadas

src/components/flatList/index.tsx
Falta el de los N° Circuito, N° Mesa, N° Electores, N° Sobres
=> Fix max numbers flatlist votes inputs /load-information index.tsx

src/components/button/index.tsx, src/components/button/types.ts, src/components/navbar/index.tsx, src/components/navbar/types.ts, src/pages/load-information/loadInformation.tsx, src/pages/verify-certificate/verifyCertificate.tsx, tailwind.config.js
+ Se agrega CloseMenuLink para mayor legibilidad + buenas practicas
+ Se fixean las rutas de Listado de mesas cargadas y Denunciar fraude
+ Se cambia texto "Inicio de sesion" por "Cerrar sesion"
=> Navbar fixes

index.html, src/components/cardLink/index.tsx, src/components/overlay/index.tsx, src/middlewares/publicRoute.tsx, src/pages/home/home.tsx, src/routes/routes.tsx
- Se cambia title a webpage
Cambios estilos /home
before:
after;
=> update home styles, change web title

src/components/navbar/index.tsx, src/pages/home/home.tsx, src/pages/total-results/totalResults.tsx
- Creo middleware publicRoute, que verifica si el usuario está autenticado y si es así lo redirije /home
- Protejo /login
- Fix css overlay
before
after
=> protect /login route when auth token exists, fix overlay on scroll

src/components/button/index.tsx, src/components/buttonClearFilter/index.tsx, src/components/buttonFilter/index.tsx, src/components/progressIndicator/index.tsx, src/components/uploadImage/index.tsx, src/pages/filter-results/filter-results.tsx, src/pages/login/login.tsx, src/pages/total-results/totalResults.tsx
En base a lo que marcó Juan, se realizan varias correcciones visuales
[TRELLO CARD](https://trello.com/c/o9YiMD4G/183-corrigiendo-errores-en-branch-design-fixes)
- Corregido botón login + colores
- Corregido botón filtros + colores
- Corregidos botónes vista filter-results + colores
- Corregido Progress Indicator
- Corregido y refactorizado botón de Cargar Imagen
=> various design fixes

src/interfaces/IDesk.ts, src/pages/desk-list/deskList.tsx, src/pages/desk-list/types.ts
+ Se refactoriza componente y se aplica los disenos basados en figma.
+ Se agraga logicas para manejar el estado de cada accordion y sus componentes visuales
https://trello.com/c/2orW7vmS/173-redise%C3%B1o-de-dropdowns-de-las-mesas-cargadas
FIGMA:
Estado cerrado
Estado abierto
Dev:
@n3-n2-n1
=> Desk list UI redesign

src/pages/login/login.tsx
Sets the loading screen as default and error when checking and adds animations
https://trello.com/c/od9fr9tb/195-fixear-flujo-de-aplicaci%C3%B3n-para-que-no-muestre-vista-de-error-primero
https://github.com/LlibertadApp/frontend/assets/43304840/c4a6d7a2-c5e4-4aae-97c1-242570a8b784
=> Login Flow Fix

src/components/uploadImage/index.tsx, src/context/CertificationContext.tsx, src/pages/load-information/loadInformation.tsx, src/pages/upload-certificate/uploadCertificate.tsx, src/pages/verify-certificate/verifyCertificate.tsx
1- Se corrije el flujo del formulario para que se carguen los datos cuando es una mesa con irregularidades y redirija correctamente a la vista de warning
2- Se corrige tipado para adaptarse a las nuevas funciones de manejo de archivos
[TRELLO CARD](https://trello.com/c/KUrZByJ5/206-fix-envio-de-mesas-irregulares-no-sigue-el-flujo-no-manda-al-server)
=> fix loadInformation to send irregular tables, fix cerificate context typing and deprecations
